spring:
  application:
    name: reserva-citas-demonio
  jackson:
    default-property-inclusion: non-null

app:
  retraso-inicial: 5000
  intervalo:
    cada-cinco-minutos: 300000
    diario-siete-am: 0 0 7 * * ? 
  uri:
    cada-cinco-minutos: https://reservacita-223020.appspot.com/daemon/cincomin
    diario-siete-am: https://reservacita-223020.appspot.com/daemon/diariosieteam
        
logging:
  level:
    pe.edu.unmsm.sistemas.servidorclinica:
      daemon: TRACE
  file: appfile.log
endpoints:  enabled: false  logfile:    enabled: true
    sensitive: false
    path: /actuator/logfile
    
    
